/* Build the shipped Starter Kit from starter-kit/pads/*.json (source of truth) into js/app/starter-kit.js.
   Browsers can't fetch JSON next to a file:// page, so the kit is bundled into a plain script the page loads.
   Order and kit name come from starter-kit/manifest.json; pads not listed there are appended alphabetically.
   Trigger keys are assigned in order (1-0 q-p a-l z-m) unless a pad already has one.
   Usage: node tools/build-starter.js */
const fs = require('fs'); const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..', '..'); const DIR = path.join(ROOT, 'starter-kit'); const PADS = path.join(DIR, 'pads');
const manifest = fs.existsSync(path.join(DIR, 'manifest.json')) ? JSON.parse(fs.readFileSync(path.join(DIR, 'manifest.json'), 'utf8')) : { name: 'Starter Kit', order: [] };
const files = fs.readdirSync(PADS).filter(f => f.endsWith('.json'));
const byFile = {}; for (const f of files) { const j = JSON.parse(fs.readFileSync(path.join(PADS, f), 'utf8')); const pads = Array.isArray(j.pads) ? j.pads : [j]; byFile[f] = pads; }
const order = []; const seen = new Set();
for (const f of manifest.order || []) { const key = f.endsWith('.json') ? f : f + '.json'; if (byFile[key]) { order.push(key); seen.add(key); } else console.warn('manifest lists missing file: ' + key); }
files.filter(f => !seen.has(f)).sort().forEach(f => order.push(f));
const KEYS = '1234567890qwertyuiopasdfghjklzxcvbnm'.split(''); const used = new Set(); const out = [];
for (const f of order) for (const p of byFile[f]) { const pad = JSON.parse(JSON.stringify(p)); delete pad._rr; if (pad.key && !used.has(pad.key)) used.add(pad.key); else pad.key = ''; pad._file = f; out.push(pad); }
for (const pad of out) { if (!pad.key) { const k = KEYS.find(k => !used.has(k)); if (k) { pad.key = k; used.add(k); } } }
const names = new Set(); for (const pad of out) { let n = pad.name, i = 2; while (names.has(n)) n = pad.name + ' ' + i++; pad.name = n; names.add(n); }
const banner = '/* GENERATED by archive/dev/tools/build-starter.js from starter-kit/pads/*.json — edit the JSON files (or export pads from the app) and rebuild; do not edit this file. */\n';
const body = 'window.Foley = window.Foley || {};\nFoley.Factory = ' + JSON.stringify({ [manifest.name || 'Starter Kit']: out.map(p => { const q = Object.assign({}, p); delete q._file; return q; }) }) + ';\n';
fs.writeFileSync(path.join(ROOT, 'js', 'app', 'starter-kit.js'), banner + body);
console.log('built js/app/starter-kit.js: "' + (manifest.name || 'Starter Kit') + '" with ' + out.length + ' pads from ' + order.length + ' files (' + used.size + ' with trigger keys)');
out.forEach((p, i) => console.log(String(i + 1).padStart(3) + '. ' + (p.key ? '[' + p.key + '] ' : '    ') + p.name.padEnd(22) + ' <- ' + p._file));
